### ISSUE TITLE
Stuck...

### ISSUE THREAD

**Issue by zedstar** [openbouffalo/buildroot_bouffalo#38]
tried to flash MCU, got to 1% and then got this....

[00:02:41.634] - EFUSE_CFG
[00:02:41.634] - BOOTHEADER_GROUP0_CFG
[00:02:41.634] - BOOTHEADER_GROUP1_CFG
[00:02:41.644] - Create bootheader using C:\Users\X\Downloads\chips\bl808\img_create_mcu/efuse_bootheader_cfg.ini
[00:02:41.644] - Updating data according to <C:\Users\X\Downloads\chips\bl808\img_create_mcu/efuse_bootheader_cfg.ini[BOOTHEADER_GROUP0_CFG]>
[00:02:41.644] - Created file len:352
[00:02:41.659] - Create bootheader using C:\Users\X\Downloads\chips\bl808\img_create_mcu/efuse_bootheader_cfg.ini
[00:02:41.659] - Updating data according to <C:\Users\X\Downloads\chips\bl808\img_create_mcu/efuse_bootheader_cfg.ini[BOOTHEADER_GROUP1_CFG]>
[00:02:41.659] - Created file len:352
[00:02:41.659] - Create efuse using C:\Users\X\Downloads\chips\bl808\img_create_mcu/efuse_bootheader_cfg.ini
[00:02:41.659] - Updating data according to <C:\Users\X\Downloads\chips\bl808\img_create_mcu/efuse_bootheader_cfg.ini[EFUSE_CFG]>
[00:02:41.659] - Created file len:256
[00:02:41.659] - Image create path: C:\Users\X\Downloads\chips\bl808\img_create_mcu
[00:02:41.674] - Config file: C:\Users\X\Downloads\chips\bl808\img_create_mcu/img_create_cfg.ini
[00:02:41.674] - Image hash is b'81b6a457b975c9861ebe100626858cc5c4da5ed3a54a4b6e843f32256c05ee54'
[00:02:41.674] - Header crc: b'1ee6be10'
[00:02:41.674] - Write flash img
[00:02:41.689] - Image hash is b'8ffa582fbeaca50ffdeabcf2305bfac575c5c4797995ea29a9d7d2ebdb29918a'
[00:02:41.689] - Header crc: b'4e4b53fe'
[00:02:41.689] - Write flash img
[00:02:41.689] - Encrypt efuse data
[00:02:41.689] - ========= eflash loader config =========
[00:02:41.719] - Version: eflash_loader_v2.4.5
[00:02:41.719] - Program Start
[00:02:41.719] - ========= eflash loader cmd arguments =========
[00:02:41.719] - None
[00:02:41.719] - Config file: C:\Users\X\Downloads\chips\bl808\eflash_loader\eflash_loader_cfg.ini
[00:02:41.719] - serial port is COM4
[00:02:41.719] - cpu_reset=False
[00:02:41.719] - chiptype: bl808
[00:02:41.719] - ========= Interface is uart =========
[00:02:41.719] - com speed: 2000000
[00:02:41.719] - Bootrom load
[00:02:41.719] - ========= get_boot_info =========
[00:02:41.719] - ========= image get bootinfo =========
[00:02:43.763] - ack is
[00:02:43.763] - Not ack OK
[00:02:43.763] - result:
[00:02:44.040] - tx rx and power off, press the machine!
[00:02:44.040] - cutoff time is 0.05
[00:02:44.093] - power on tx and rx
[00:02:45.140] - reset cnt: 0, reset hold: 0.05, shake hand delay: 0.1
[00:02:45.140] - clean buf
[00:02:45.165] - send sync
[00:02:45.680] - ack is 4f4b
[00:02:45.740] - shake hand success
[00:02:46.240] - data read is b'01000808000000000b14c1026d1d35cf0eb456002ff4fb18'
[00:02:46.240] - ========= ChipID: b40ecf351d6d =========
[00:02:46.240] - Get bootinfo time cost(ms): 4521.703369140625
[00:02:46.240] - clock para file: C:\Users\X\Downloads\chips/bl808/efuse_bootheader/clock_para.bin
[00:02:46.240] - change bdrate: 2000000
[00:02:46.240] - Clock PLL set
[00:02:46.240] - clock para:
[00:02:46.240] - 5043464707040000030103000102000201010001010101010a894b86
[00:02:46.240] - Set clock time cost(ms): 0.0
[00:02:46.426] - Read mac addr
[00:02:46.426] - flash set para
[00:02:46.426] - get flash pin cfg from bootinfo: 0x04
[00:02:46.426] - set flash cfg: 14104
[00:02:46.426] - Set flash config
[00:02:46.426] - Set para time cost(ms): 0.0
[00:02:46.426] - ========= flash read jedec ID =========
[00:02:46.426] - Read flash jedec ID
[00:02:46.426] - flash jedec id: ef601800
[00:02:46.426] - Finished
[00:02:46.426] - Program operation
[00:02:46.426] - Dealing Index 0
[00:02:46.426] - ========= programming chips\bl808\img_create_mcu\bootinfo_group0.bin to 0x00000000
[00:02:46.426] - flash para file: C:\Users\X\Downloads\chips/bl808/efuse_bootheader/flash_para.bin
[00:02:46.426] - Set flash config
[00:02:46.441] - Set para time cost(ms): 14.715087890625
[00:02:46.441] - ========= flash load =========
[00:02:46.441] - ========= flash erase =========
[00:02:46.441] - Erase flash from 0x0 to 0x663
[00:02:46.481] - Erase time cost(ms): 40.005859375
[00:02:46.511] - Load 1636/1636 {"progress":100}
[00:02:46.511] - Load 1636/1636 {"progress":100}
[00:02:46.511] - Write check
[00:02:46.541] - Flash load time cost(ms): 45.00048828125
[00:02:46.541] - Finished
[00:02:46.541] - Sha caled by host: cc8396f8276741b843f35aa3c850031f62b77070700197c65a1806033d275947
[00:02:46.541] - xip mode Verify
[00:02:46.541] - Read Sha256/1636
[00:02:46.541] - Flash xip readsha time cost(ms): 0.0
[00:02:46.541] - Finished
[00:02:46.541] - Sha caled by dev: cc8396f8276741b843f35aa3c850031f62b77070700197c65a1806033d275947
[00:02:46.541] - Verify success
[00:02:46.551] - Dealing Index 1
[00:02:46.551] - ========= programming chips\bl808\img_create_mcu\bootinfo_group1.bin to 0x00001000
[00:02:46.566] - flash para file: C:\Users\X\Downloads\chips/bl808/efuse_bootheader/flash_para.bin
[00:02:46.566] - Set flash config
[00:02:46.566] - Set para time cost(ms): 0.0
[00:02:46.566] - ========= flash load =========
[00:02:46.566] - ========= flash read =========
[00:02:52.576] - Read data error,maybe not get excepted length
[00:02:52.576] - Retry
[00:02:54.576] - ack is
[00:02:54.576] - Not ack OK
[00:02:54.576] - Retry
[00:02:56.577] - ack is
[00:02:56.577] - Not ack OK
[00:02:56.577] - Retry
[00:02:58.578] - ack is
[00:02:58.578] - Not ack OK
[00:02:58.578] - ErrorCode: 0035, ErrorMsg: BFLB FLASH READ FAIL
[00:02:58.578] - 'NoneType' object is not subscriptable
Traceback (most recent call last):
File "libs\bflb_eflash_loader.py", line 3634, in efuse_flash_loader_do
File "libs\bflb_eflash_loader.py", line 2185, in flash_load_specified
File "libs\bflb_eflash_loader.py", line 2060, in flash_load_opt
TypeError: 'NoneType' object is not subscriptable
[00:02:58.578] - Burn Retry
[00:02:58.578] - 0
[00:02:58.578] - Burn return with retry fail

**Comment by Fishwaldo** [comment]
Try lowering the baudrate and/or enabling the "Chip Erase" option on the right side of BLDevCube

**Comment by zedstar** [comment]
reducing baud rate did it! thanks heaps.
